services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./secrets/firebase-key.json:/app/firebase-key.json
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app           # sync source
      - /app/node_modules         # avoid mounting over container's node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
